name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # تشخیصی: لیست پروژه‌ها
      - name: Show Gradle projects
        run: ./gradlew projects

      # تشخیصی: لیست تسک‌های merchant-app
      - name: Show merchant-app tasks
        run: ./gradlew :merchant-app:tasks --all

      # بیلد consumer
      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # بیلد merchant
      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
