name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ✅ بوت‌استرپ مطمئن Gradle Wrapper بدون نیاز به gradle سیستم
      - name: Bootstrap Gradle Wrapper JAR if missing
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Fetching official Gradle 8.9 jar..."
            curl -sSL -o gradle-8.9-bin.zip https://services.gradle.org/distributions/gradle-8.9-bin.zip
            # فقط فایل jar را از داخل زیپ استخراج می‌کنیم:
            unzip -p gradle-8.9-bin.zip gradle-8.9/lib/plugins/gradle-wrapper-8.9.jar > gradle/wrapper/gradle-wrapper.jar
            rm -f gradle-8.9-bin.zip
            echo "Wrapper JAR installed at gradle/wrapper/gradle-wrapper.jar"
          fi

          # اگر properties وجود ندارد، می‌سازیم
          if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
            cat > gradle/wrapper/gradle-wrapper.properties <<'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
            echo "Created gradle/wrapper/gradle-wrapper.properties"
          fi

      - name: Ensure Gradle wrapper is executable
        run: chmod +x gradlew

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace

      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-Debug-APK
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-Debug-APK
          path: merchant-app/build/outputs/apk/debug/*.apk
