name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # مجوز اجرای Gradle Wrapper
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # ------------------ تشخیص ساختار پروژه ------------------
      - name: Show repo root
        run: |
          pwd
          ls -la
          echo "----- settings.gradle* -----"
          (cat settings.gradle.kts || true)
          (cat settings.gradle || true)

      - name: Show module trees
        run: |
          echo "----- consumer-app tree -----"
          ls -la consumer-app || true
          echo "----- merchant-app tree -----"
          ls -la merchant-app || true
          echo "----- build files existence -----"
          [ -f merchant-app/build.gradle.kts ] && echo "merchant-app/build.gradle.kts exists"
          [ -f merchant-app/build.gradle ] && echo "merchant-app/build.gradle exists"
          [ -f consumer-app/build.gradle.kts ] && echo "consumer-app/build.gradle.kts exists"
          [ -f consumer-app/build.gradle ] && echo "consumer-app/build.gradle exists"

      - name: Show Gradle wrapper files
        run: |
          ls -la gradle/wrapper || true
          cat gradle/wrapper/gradle-wrapper.properties || true

      - name: Show Gradle version (wrapper)
        run: ./gradlew --version

      # ------------------ تشخیص Gradle: لیست پروژه‌ها و تسک‌ها ------------------
      - name: Show projects
        run: ./gradlew projects --stacktrace --no-daemon

      - name: Show consumer-app tasks
        run: ./gradlew :consumer-app:tasks --all --stacktrace --no-daemon

      - name: Show merchant-app tasks
        run: ./gradlew :merchant-app:tasks --all --stacktrace --no-daemon

      - name: Show merchant-app properties
        run: ./gradlew :merchant-app:properties --stacktrace --no-daemon

      # ------------------ بیلد هر دو APK ------------------
      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace --no-daemon

      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace --no-daemon

      # ------------------ انتشار آرتیفکت‌ها ------------------
      - name: Upload Consumer APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: |
            consumer-app/build/outputs/apk/debug/*.apk
            consumer-app/build/outputs/apk/*/debug/*.apk
          if-no-files-found: warn

      - name: Upload Merchant APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: |
            merchant-app/build/outputs/apk/debug/*.apk
            merchant-app/build/outputs/apk/*/debug/*.apk
          if-no-files-found: warn
