name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Consumer & Merchant Debug
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: consumer-debug
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: merchant-debug
          path: merchant-app/build/outputs/apk/debug/*.apk
