name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Bootstrap Gradle Wrapper JAR if missing
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Fetching from Gradle..."
            curl -sL https://services.gradle.org/distributions/gradle-8.9-bin.zip -o gradle-8.9-bin.zip
            unzip -p gradle-8.9-bin.zip gradle-8.9/lib/plugins/gradle-wrapper-8.9.jar > gradle/wrapper/gradle-wrapper.jar
            rm -f gradle-8.9-bin.zip
          fi
        working-directory: SOMA_demo_APP

      - name: Ensure Gradle wrapper files exist
        working-directory: SOMA_demo_APP
        run: |
          chmod +x gradlew

      - name: Show Gradle version (wrapper)
        working-directory: SOMA_demo_APP
        run: ./gradlew --version

      - name: Build Consumer Debug APK
        working-directory: SOMA_demo_APP
        run: ./gradlew :consumer-app:assembleDebug --stacktrace

      - name: Build Merchant Debug APK
        working-directory: SOMA_demo_APP
        run: ./gradlew :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-Debug-APK
          path: SOMA_demo_APP/consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-Debug-APK
          path: SOMA_demo_APP/merchant-app/build/outputs/apk/debug/*.apk
