name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # اکشن رسمی گرادل (کش خودکار + اسکن اختیاری)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # اگر gradlew داخل رپو هست لازم می‌شود
      - name: Grant Gradle Wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      # اگر هر دو ماژول دارید (consumer-app و merchant-app)
      - name: Build Consumer & Merchant (Debug)
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug

      # آپلود خروجی‌ها با v4 (سازگار با تغییرات جدید گیت‌هاب)
      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-APKs
          path: |
            consumer-app/build/outputs/apk/debug/*.apk
            consumer-app/build/outputs/apk/**/debug/*.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-APKs
          path: |
            merchant-app/build/outputs/apk/debug/*.apk
            merchant-app/build/outputs/apk/**/debug/*.apk
