name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Gradle را بدون wrapper روی Runner نصب می‌کند
      - name: Set up Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"
          cache-disabled: false

      # هرچی wrapper خراب هست پاک و یک wrapper سالم می‌سازیم
      - name: Regenerate Gradle Wrapper (8.7)
        run: |
          rm -f gradle/wrapper/gradle-wrapper.jar || true
          rm -f gradle/wrapper/gradle-wrapper.properties || true
          mkdir -p gradle/wrapper
          gradle wrapper --gradle-version 8.7 --distribution-type bin --no-daemon
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # برای اطمینان: اگر Wrapper سالم باشد، این لیست پروژه‌ها را نشان می‌دهد
      - name: Show projects
        run: ./gradlew projects

      # بیلد کانسومر
      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # بیلد مرچنت
      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
