name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # فعال کردن دکمه Run workflow در تب Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: false
          gradle-version: 8.7

      - name: Build Consumer & Merchant Debug
        run: |
          gradle --version
          gradle :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug
          path: merchant-app/build/outputs/apk/debug/*.apk
