name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # دانلود مستقیم gradle-wrapper.jar اگر نبود
      - name: Bootstrap Gradle Wrapper JAR if missing
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Downloading from Gradle repo..."
            curl -sSL -o gradle/wrapper/gradle-wrapper.jar \
              https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-wrapper/8.9/gradle-wrapper-8.9.jar
            ls -l gradle/wrapper
          fi

      - name: Ensure Gradle wrapper is executable
        run: chmod +x gradlew

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace

      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-Debug-APK
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-Debug-APK
          path: merchant-app/build/outputs/apk/debug/*.apk
