name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Install Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle-8.7-bin.zip
          unzip gradle-8.7-bin.zip -d /opt/gradle
          export PATH=/opt/gradle/gradle-8.7/bin:$PATH
          gradle --version

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew

      - name: Build Consumer & Merchant Debug
        run: |
          ./gradlew --version
          ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug
          path: merchant-app/build/outputs/apk/debug/*.apk
