name: Build APKs (SOMA Offline Demo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # استفاده از Gradle Action رسمی — نیازی به gradlew فیزیکی نیست
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # اجرای بیلد با Gradle Action (نه فایل gradlew)
      - name: Build Consumer & Merchant (Debug)
        run: |
          gradle :consumer-app:assembleDebug
          gradle :merchant-app:assembleDebug

      # آپلود خروجی‌ها با نسخه جدید اکشن
      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-APKs
          path: |
            consumer-app/build/outputs/apk/debug/*.apk
            consumer-app/build/outputs/apk/**/debug/*.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-APKs
          path: |
            merchant-app/build/outputs/apk/debug/*.apk
            merchant-app/build/outputs/apk/**/debug/*.apk
