name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Prepare Gradle Wrapper (force create if missing)
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper not found — generating..."
            curl -L -o ${RUNNER_TEMP}/gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q ${RUNNER_TEMP}/gradle-8.7-bin.zip -d ${RUNNER_TEMP}
            ${RUNNER_TEMP}/gradle-8.7/bin/gradle wrapper --gradle-version 8.7 --distribution-type all
          fi
          chmod +x ./gradlew
          ls -R gradle/wrapper || true

      - name: Verify Gradle version
        run: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build Consumer & Merchant Debug
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
