name: Build Consumer & Merchant (Debug)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Consumer APK
        run: flutter build apk --debug --target lib/consumer_main.dart

      - name: Build Merchant APK
        run: flutter build apk --debug --target lib/merchant_main.dart

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app
          path: build/app/outputs/flutter-apk/app-debug.apk
