name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify Gradle version
        run: ./gradlew --version

      # ساخت هر دو ماژول
      - name: Build Consumer & Merchant Debug
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      # آپلود APK ماژول consumer
      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # آپلود APK ماژول merchant
      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
