name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Download Gradle 8.9
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.9/bin" >> $GITHUB_PATH

      - name: Regenerate Gradle Wrapper (8.9)
        run: |
          gradle wrapper --gradle-version 8.9 --distribution-type bin --no-daemon

      - name: Make gradlew executable
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      - name: Show Gradle projects
        run: ./gradlew projects

      - name: Show merchant-app tasks
        run: ./gradlew :merchant-app:tasks --all

      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
