: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Build Consumer & Merchant
        run: |
          ./gradlew :consumer-app:clean :consumer-app:assembleDebug \
                     :merchant-app:clean :merchant-app:assembleDebug

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v3
        with:
          name: SOMA_Consumer_APK
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v3
        with:
          name: SOMA_Merchant_APK
          path: merchant-app/build/outputs/
