name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Consumer & Merchant (Debug)
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-APKs
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-APKs
          path: merchant-app/build/outputs/apk/debug/*.apk
