name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Consumer APK
        run: flutter build apk --target lib/consumer_main.dart --debug

      - name: Build Merchant APK
        run: flutter build apk --target lib/merchant_main.dart --debug

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Consumer-APKs
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: Merchant-APKs
          path: build/app/outputs/flutter-apk/app-debug.apk
