name: Build Consumer & Merchant (Debug)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up job
      - name: Set up job
        run: echo "Setting up job"

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Install dependencies
      - name: Install dependencies
        working-directory: SOMA_demo_APP
        run: flutter pub get

      # Build Consumer APK
      - name: Build Consumer APK
        working-directory: SOMA_demo_APP
        run: flutter build apk --debug --target lib/consumer_main.dart

      # Build Merchant APK
      - name: Build Merchant APK
        working-directory: SOMA_demo_APP
        run: flutter build apk --debug --target lib/merchant_main.dart

      # Upload APKs (optional)
      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v3
        with:
          name: consumer-apk
          path: SOMA_demo_APP/build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v3
        with:
          name: merchant-apk
          path: SOMA_demo_APP/build/app/outputs/flutter-apk/app-debug.apk

      # Complete job
      - name: Complete job
        run: echo "Build and Upload Completed!"
