name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # اکشن رسمی گرادل (سیستم گرادل را فراهم می‌کند)
      - name: Setup Gradle (tool + cache)
        uses: gradle/actions/setup-gradle@v3

      # اگر jar نبود، wrapper را می‌سازد (با مسیر درست gradle/wrapper)
      - name: Prepare Gradle Wrapper (create if missing)
        run: |
          if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "Gradle wrapper JAR missing. Generating..."
            gradle wrapper --gradle-version 8.7
          fi

      # دسترسی اجرایی به اسکریپت‌های wrapper
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify Gradle version
        run: ./gradlew --version

      # بیلد هر دو ماژول در حالت Debug
      - name: Build Consumer & Merchant Debug
        run: ./gradlew :consumer-app:assembleDebug :merchant-app:assembleDebug --stacktrace

      # آپلود خروجی‌ها به آرتیفکت
      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-apks
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-apks
          path: merchant-app/build/outputs/apk/debug/*.apk
