name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # همه دستورات در پوشه‌ی پروژه اجرا شوند
    defaults:
      run:
        working-directory: SOMA_demo_APP

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # اگر gradle-wrapper.jar نیست، دانلود و در مسیر درست قرار بده
      - name: Bootstrap Gradle Wrapper JAR if missing
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Fetching from Gradle 8.9 distribution..."
            curl -sL https://services.gradle.org/distributions/gradle-8.9-bin.zip -o gradle-8.9-bin.zip
            unzip -p gradle-8.9-bin.zip gradle-8.9/lib/plugins/gradle-wrapper-8.9.jar > gradle/wrapper/gradle-wrapper.jar
            rm -f gradle-8.9-bin.zip
          fi

      - name: Ensure gradle wrapper files exist
        run: |
          ls -la
          ls -la gradle || true
          ls -la gradle/wrapper || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show Gradle version (wrapper)
        run: ./gradlew --version

      - name: Show projects
        run: ./gradlew projects

      # (اختیاری) اطمینان از هم‌خوانی نسخهٔ رپر با 8.9
      - name: Regenerate wrapper to 8.9 (bin)
        run: ./gradlew wrapper --gradle-version 8.9 --distribution-type bin --no-daemon

      - name: Build Consumer Debug APK
        run: ./gradlew :consumer-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Consumer APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: consumer-app-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Build Merchant Debug APK
        run: ./gradlew :merchant-app:assembleDebug --stacktrace --no-daemon

      - name: Upload Merchant APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: merchant-app-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
